#!/usr/bin/env bash
# ============================================================
# Step 5: Generate .env File
#
# This script collects all the Azure resource IDs created in
# steps 1–4 and generates the .env file that the FastAPI
# application needs to run.
#
# Prerequisites:
#   - Steps 1–4 completed
#   - Azure CLI installed and logged in
#
# Usage:
#   ./setup/05_generate_env.sh
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/config.sh"

require_cmd az
require_az_login

step "Step 5: Generate .env File"

# ── Load IDs from previous steps ──────────────────────────────
load_id() {
    local file="$SCRIPT_DIR/$1"
    if [[ ! -f "$file" ]]; then
        fail "File '$file' not found. Did you run the previous steps?"
    fi
    cat "$file"
}

CLIENT_ID=$(load_id ".app_client_id")
READER_GROUP_ID=$(load_id ".reader_group_id")
WRITER_GROUP_ID=$(load_id ".writer_group_id")

# Get tenant ID directly from Azure CLI
TENANT_ID=$(get_tenant_id)
if [[ -z "$TENANT_ID" ]]; then
    fail "Could not determine tenant ID. Are you logged in?"
fi

info "Collected all configuration values:"
info "  Tenant ID:       $TENANT_ID"
info "  Client ID:       $CLIENT_ID"
info "  Reader Group ID: $READER_GROUP_ID"
info "  Writer Group ID: $WRITER_GROUP_ID"

# ── Generate .env file ────────────────────────────────────────
ENV_FILE="$REPO_ROOT/$ENV_OUTPUT_FILE"

if [[ -f "$ENV_FILE" ]]; then
    warn ".env file already exists at $ENV_FILE"
    echo ""
    read -p "  Overwrite? (y/N): " OVERWRITE
    if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
        info "Keeping existing .env file."
        exit 0
    fi
fi

info "Writing .env file to $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# ============================================================
# Azure Entra ID Configuration
# Generated by setup/05_generate_env.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# ============================================================

# Your Azure Entra ID tenant ID (Directory ID)
AZURE_TENANT_ID=$TENANT_ID

# The Application (client) ID from your App Registration
AZURE_CLIENT_ID=$CLIENT_ID

# Object ID of the "api-readers" security group
AZURE_READER_GROUP_ID=$READER_GROUP_ID

# Object ID of the "api-writers" security group
AZURE_WRITER_GROUP_ID=$WRITER_GROUP_ID
EOF

ok ".env file generated successfully"

# ── Verify .gitignore includes .env ───────────────────────────
GITIGNORE="$REPO_ROOT/.gitignore"
if [[ -f "$GITIGNORE" ]]; then
    if grep -q "^\.env$" "$GITIGNORE"; then
        ok ".gitignore already excludes .env"
    else
        warn ".gitignore does not exclude .env — this is a security risk!"
        warn "  Add '.env' to .gitignore to prevent committing secrets."
    fi
fi

# ── Summary ───────────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}${GREEN}  ✓ .env File Generated${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${BOLD}File:${NC} $ENV_FILE"
echo ""
echo -e "  ${CYAN}You can now start the API:${NC}"
echo -e "    source .venv/bin/activate"
echo -e "    uvicorn app.main:app --reload"
echo ""
echo -e "  ${CYAN}Then open:${NC} http://localhost:8000/docs"
echo ""
