#!/usr/bin/env bash
# ============================================================
# Step 5: Generate .env File
#
# This script collects all the Azure resource IDs created in
# steps 1–4 and generates the .env file that the FastAPI
# application needs to run.
#
# Prerequisites:
#   - Steps 1–4 completed
#   - Azure CLI installed and logged in
#
# Usage:
#   ./setup/05_generate_env.sh
# ============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPT_DIR/config.sh"

require_cmd az
require_az_login

step "Step 5: Generate .env File"

# ── Load IDs from previous steps ──────────────────────────────
load_id() {
    local file="$SCRIPT_DIR/$1"
    if [[ ! -f "$file" ]]; then
        fail "File '$file' not found. Did you run the previous steps?"
    fi
    cat "$file"
}

API_APP_ID=$(load_id ".app_client_id")
READER_GROUP_ID=$(load_id ".reader_group_id")
WRITER_GROUP_ID=$(load_id ".writer_group_id")

# Load Client App IDs
if [[ ! -f "$SCRIPT_DIR/.client_app_client_id" ]]; then
    error "File '$SCRIPT_DIR/.client_app_client_id' not found. Did you run 06_create_client_app.sh?"
    exit 1
fi
CLIENT_ID=$(cat "$SCRIPT_DIR/.client_app_client_id")

if [[ ! -f "$SCRIPT_DIR/.cert_thumbprint" ]]; then
    error "File '$SCRIPT_DIR/.cert_thumbprint' not found. Did you run 07_configure_certificates.sh?"
    exit 1
fi
CERT_THUMBPRINT=$(cat "$SCRIPT_DIR/.cert_thumbprint")

# Get tenant ID directly from Azure CLI
TENANT_ID=$(get_tenant_id)
if [[ -z "$TENANT_ID" ]]; then
    fail "Could not determine tenant ID. Are you logged in?"
fi

info "Collected all configuration values:"
ok "  Tenant ID:       $TENANT_ID"
ok "  API Client ID:   $API_APP_ID"
ok "  Reader Group ID: $READER_GROUP_ID"
ok "  Writer Group ID: $WRITER_GROUP_ID"
ok "  CLI Client ID:   $CLIENT_ID"
ok "  Cert Thumbprint: $CERT_THUMBPRINT"

# ── Generate .env file ────────────────────────────────────────
ENV_FILE="$REPO_ROOT/$ENV_OUTPUT_FILE"

if [[ -f "$ENV_FILE" ]]; then
    warn ".env file already exists at $ENV_FILE"
    echo ""
    read -p "  Overwrite? (y/N): " OVERWRITE
    if [[ "$OVERWRITE" =~ ^[Yy]$ ]]; then
        info "Overwriting .env file..."
    else
        info "Keeping existing .env file."
        ENV_FILE=""
    fi
fi

if [[ -n "$ENV_FILE" ]]; then
    info "Writing .env file to $ENV_FILE..."
    cat > "$ENV_FILE" << EOF
# ============================================================
# Azure Entra ID Configuration
# Generated by setup/05_generate_env.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# ============================================================

# Your Azure Entra ID tenant ID (Directory ID)
AZURE_TENANT_ID=$TENANT_ID

# The Client ID (Application ID) of your App Registration
AZURE_CLIENT_ID=$API_APP_ID

# Object ID of the "api-readers" security group
AZURE_READER_GROUP_ID=$READER_GROUP_ID

# Object ID of the "api-writers" security group
AZURE_WRITER_GROUP_ID=$WRITER_GROUP_ID
EOF
    ok ".env file generated successfully"
fi

# ── Generate .env.client file ─────────────────────────────────
if [[ -n "$CLIENT_ID" && -n "$CERT_THUMBPRINT" ]]; then
    CLIENT_ENV_FILE="$REPO_ROOT/.env.client"
    
    cat > "$CLIENT_ENV_FILE" << EOF
# ============================================================
# Client Credentials Configuration
# Generated by setup/05_generate_env.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# ============================================================

# Your Azure Entra ID tenant ID (Directory ID)
AZURE_TENANT_ID=$TENANT_ID

# The Client ID of the automated CLI app
CLIENT_ID=$CLIENT_ID

# The Certificate Thumbprint for the automated CLI app
CERT_THUMBPRINT=$CERT_THUMBPRINT

# The API's Application ID URI (the scope the client requests)
API_SCOPE=api://$API_APP_ID/.default
EOF
    ok ".env.client file generated successfully"
fi

# ── Verify .gitignore includes .env ───────────────────────────
GITIGNORE="$REPO_ROOT/.gitignore"
if [[ -f "$GITIGNORE" ]]; then
    if grep -q "^\.env$" "$GITIGNORE"; then
        ok ".gitignore already excludes .env"
    else
        warn ".gitignore does not exclude .env — this is a security risk!"
        warn "  Add '.env' to .gitignore to prevent committing secrets."
    fi
fi

# ── Summary ───────────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}${GREEN}  ✓ .env File Generated${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${BOLD}File:${NC} $ENV_FILE"
echo ""
echo -e "  ${CYAN}You can now start the API:${NC}"
echo -e "    source .venv/bin/activate"
echo -e "    uvicorn app.main:app --reload"
echo ""
echo -e "  ${CYAN}Then open:${NC} http://localhost:8000/docs"
echo ""
